services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - stripe-cli
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: listen --skip-verify --forward-to web:8000/payment/webhooks/stripe/
    env_file:
      - .env.stripe
    networks:
      - default

  db:
    container_name: "postgresql"
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file: .env.postgresql