# Generated by Django 5.2.5 on 2025-08-26 18:03

import ProductService.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0003_customuser_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='Listing',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='ProductService.productcategory'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=ProductService.models.get_image_upload_path),
        ),
    ]
