# Generated by Django 5.2.5 on 2025-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0004_rename_listing_productimages_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default-user-photo.png', null=True, upload_to='profile_photos/'),
        ),
    ]
