# Generated by Django 5.2.5 on 2025-08-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0005_alter_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='stock',
        ),
    ]
