# Generated by Django 5.2.5 on 2025-08-28 15:04

import ProductService.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0006_remove_listing_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ProductService.models.get_image_upload_path),
        ),
    ]
