# Generated by Django 5.2.5 on 2025-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0007_alter_productimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
