# Generated by Django 5.2.5 on 2025-08-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at_order_product_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
    ]
